volumes:
  website:
    driver: local
    driver_opts:
      type:   'none'
      o:      'bind'
      device: '/home/jhughes/data/website'
  database:
    driver: local
    driver_opts:
      type:   'none'
      o:      'bind'
      device: '/home/jhughes/data/database'

networks:
  42_inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    secrets:
      - wp_db_pass
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - 42_inception
  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    secrets:
      - wp_db_pass
      - wp_admin_pass
      - wp_user_pass
    volumes:
      - website:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - 42_inception
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "443:443"
    volumes:
      - website:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    env_file:
      - .env
    networks:
      - 42_inception

secrets:
  wp_db_pass:
    file: ../secrets/wp_db.pass
  wp_admin_pass:
    file: ../secrets/wp_admin.pass
  wp_user_pass:
    file: ../secrets/wp_user.pass